// <auto-generated />
namespace mti_tech_interview_examination.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201712230839 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201712230839));
        
        string IMigrationMetadata.Id
        {
            get { return "201712230139564_201712230839"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
